apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: hubble-generate-certs
    app.kubernetes.io/part-of: cilium
    k8s-app: hubble-generate-certs
  name: hubble-generate-certs-13fc18f475
  namespace: cilium
spec:
  template:
    metadata:
      labels:
        k8s-app: hubble-generate-certs
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --ca-generate=true
        - --ca-reuse-secret
        - --ca-secret-namespace=cilium
        - --ca-secret-name=cilium-ca
        - --ca-common-name=Cilium CA
        command:
        - /usr/bin/cilium-certgen
        env:
        - name: CILIUM_CERTGEN_CONFIG
          value: "certs:\n- name: hubble-server-certs\n  namespace: cilium\n  commonName:\
            \ \"*.default.hubble-grpc.cilium.io\"\n  hosts:\n  - \"*.default.hubble-grpc.cilium.io\"\
            \n  usage:\n  - signing\n  - key encipherment\n  - server auth\n  - client\
            \ auth\n  validity: 8760h\n- name: hubble-relay-client-certs\n  namespace:\
            \ cilium\n  commonName: \"*.hubble-relay.cilium.io\"\n  hosts:\n  - \"\
            *.hubble-relay.cilium.io\"\n  usage:\n  - signing\n  - key encipherment\n\
            \  - client auth\n  validity: 8760h\n"
        image: quay.io/cilium/certgen:v0.4.3@sha256:d63d1cb3ee6db2167cb1ca9e7e31f30b6197846fcf42505d8f59e2f090a42c86
        imagePullPolicy: IfNotPresent
        name: certgen
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      hostNetwork: false
      restartPolicy: OnFailure
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: hubble-generate-certs
