apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: fission-validating-webhooks
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU9pUTBlT0pRalBZYlA3cTFTTjNKdXN3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXdOekExTWpOYUZ3MHpNVEExTURVdwpOekExTWpOYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXZ6WFRvVFlDcHdsdmdId2NaaWtWK0QKYmZRTUVJbzhRRnBsaGtyblFtbVpsNDk4Q3cyRnlReitqYlNESlRhNHNQR2QrcDVvUTFHeHRoTGZxbTB0SVFDZwp5NnNrUi9UNEl2enZ0OXhCOGlBTmVyeklYQTcwQU5IUWdkYXNhMTlnaTJtcXhTbS9LU3dLWEpoTGdPT01ENW5xCmNOSEJBd2R0SEhxdDBIa3pxd0d3YWZqcHZVc2VSQnRVVWNRKzcxL3dIdlNKMm5xbkhhcXNaaVoxYjRvNHEyS0MKTXNSVEZ6Tmt3U2p3d05lYW9SVTZ4TXNqcGwxVFdhYTVLU0Z6bXpsb2VzZFBQdS9DZTRtSzJGMkpkQTJpVGxZaApUL1dDWUwxSU5UNjZVWDFyN1J4RnRnUU5TWnhTN3M3WlA2ZmxTQW42NHBWRnZleXlJaWRjeUh5Zjc4bzdjWDhDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVTGh1WDVROWtYVCs2Rmc1bApkQ05qYkhraytWMHdVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFyeDJqTzk1NFV0RjhWV1hnaTcwZWd3dDUwR3Y1TlZlM0RzYkQwaUlJczVqbwpuR2hYMFB6bjl2SDNyTjBCcmcxQ0cwOEhqSk5ka0dmNjA0UEoxMHI2R3Q4NVo3aWlKZTJ4QjcvcUdSbzR5MjBmCkVpZkpYTExsZEdvbFZIc2s5eDBMNGlQeVl1di9nNUl6NzlpdmFHR1FqOVNFWUxQZ1M2T3NtcUtnNitoY1IyWFcKSzZrdkpEYTNtYXJQcVlmRzFMUEFVbExWazNSRHJxamFVZ3F3MnhDV3UvZ1BmaXZiQUVsK0tCeVo1ZnNKM0N6RwpTVnFuRDNBMHJqblk1QTdMaXd6QUUyR1JHNVRrZy9nT0N1SEFKVkwxcEpaNVlEamRKdTNueDhyMEc1U0tSVHVHCjBSYlZKcEtkQmtpZ3BtaTZBMDRqckZKNWpFRm9WQW51WSt1ZFdxL0FYUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-environment
  failurePolicy: Fail
  name: venvironment.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - environments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU9pUTBlT0pRalBZYlA3cTFTTjNKdXN3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXdOekExTWpOYUZ3MHpNVEExTURVdwpOekExTWpOYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXZ6WFRvVFlDcHdsdmdId2NaaWtWK0QKYmZRTUVJbzhRRnBsaGtyblFtbVpsNDk4Q3cyRnlReitqYlNESlRhNHNQR2QrcDVvUTFHeHRoTGZxbTB0SVFDZwp5NnNrUi9UNEl2enZ0OXhCOGlBTmVyeklYQTcwQU5IUWdkYXNhMTlnaTJtcXhTbS9LU3dLWEpoTGdPT01ENW5xCmNOSEJBd2R0SEhxdDBIa3pxd0d3YWZqcHZVc2VSQnRVVWNRKzcxL3dIdlNKMm5xbkhhcXNaaVoxYjRvNHEyS0MKTXNSVEZ6Tmt3U2p3d05lYW9SVTZ4TXNqcGwxVFdhYTVLU0Z6bXpsb2VzZFBQdS9DZTRtSzJGMkpkQTJpVGxZaApUL1dDWUwxSU5UNjZVWDFyN1J4RnRnUU5TWnhTN3M3WlA2ZmxTQW42NHBWRnZleXlJaWRjeUh5Zjc4bzdjWDhDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVTGh1WDVROWtYVCs2Rmc1bApkQ05qYkhraytWMHdVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFyeDJqTzk1NFV0RjhWV1hnaTcwZWd3dDUwR3Y1TlZlM0RzYkQwaUlJczVqbwpuR2hYMFB6bjl2SDNyTjBCcmcxQ0cwOEhqSk5ka0dmNjA0UEoxMHI2R3Q4NVo3aWlKZTJ4QjcvcUdSbzR5MjBmCkVpZkpYTExsZEdvbFZIc2s5eDBMNGlQeVl1di9nNUl6NzlpdmFHR1FqOVNFWUxQZ1M2T3NtcUtnNitoY1IyWFcKSzZrdkpEYTNtYXJQcVlmRzFMUEFVbExWazNSRHJxamFVZ3F3MnhDV3UvZ1BmaXZiQUVsK0tCeVo1ZnNKM0N6RwpTVnFuRDNBMHJqblk1QTdMaXd6QUUyR1JHNVRrZy9nT0N1SEFKVkwxcEpaNVlEamRKdTNueDhyMEc1U0tSVHVHCjBSYlZKcEtkQmtpZ3BtaTZBMDRqckZKNWpFRm9WQW51WSt1ZFdxL0FYUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-function
  failurePolicy: Fail
  name: vfunction.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - functions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU9pUTBlT0pRalBZYlA3cTFTTjNKdXN3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXdOekExTWpOYUZ3MHpNVEExTURVdwpOekExTWpOYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXZ6WFRvVFlDcHdsdmdId2NaaWtWK0QKYmZRTUVJbzhRRnBsaGtyblFtbVpsNDk4Q3cyRnlReitqYlNESlRhNHNQR2QrcDVvUTFHeHRoTGZxbTB0SVFDZwp5NnNrUi9UNEl2enZ0OXhCOGlBTmVyeklYQTcwQU5IUWdkYXNhMTlnaTJtcXhTbS9LU3dLWEpoTGdPT01ENW5xCmNOSEJBd2R0SEhxdDBIa3pxd0d3YWZqcHZVc2VSQnRVVWNRKzcxL3dIdlNKMm5xbkhhcXNaaVoxYjRvNHEyS0MKTXNSVEZ6Tmt3U2p3d05lYW9SVTZ4TXNqcGwxVFdhYTVLU0Z6bXpsb2VzZFBQdS9DZTRtSzJGMkpkQTJpVGxZaApUL1dDWUwxSU5UNjZVWDFyN1J4RnRnUU5TWnhTN3M3WlA2ZmxTQW42NHBWRnZleXlJaWRjeUh5Zjc4bzdjWDhDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVTGh1WDVROWtYVCs2Rmc1bApkQ05qYkhraytWMHdVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFyeDJqTzk1NFV0RjhWV1hnaTcwZWd3dDUwR3Y1TlZlM0RzYkQwaUlJczVqbwpuR2hYMFB6bjl2SDNyTjBCcmcxQ0cwOEhqSk5ka0dmNjA0UEoxMHI2R3Q4NVo3aWlKZTJ4QjcvcUdSbzR5MjBmCkVpZkpYTExsZEdvbFZIc2s5eDBMNGlQeVl1di9nNUl6NzlpdmFHR1FqOVNFWUxQZ1M2T3NtcUtnNitoY1IyWFcKSzZrdkpEYTNtYXJQcVlmRzFMUEFVbExWazNSRHJxamFVZ3F3MnhDV3UvZ1BmaXZiQUVsK0tCeVo1ZnNKM0N6RwpTVnFuRDNBMHJqblk1QTdMaXd6QUUyR1JHNVRrZy9nT0N1SEFKVkwxcEpaNVlEamRKdTNueDhyMEc1U0tSVHVHCjBSYlZKcEtkQmtpZ3BtaTZBMDRqckZKNWpFRm9WQW51WSt1ZFdxL0FYUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-httptrigger
  failurePolicy: Fail
  name: vhttptrigger.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - httptriggers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU9pUTBlT0pRalBZYlA3cTFTTjNKdXN3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXdOekExTWpOYUZ3MHpNVEExTURVdwpOekExTWpOYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXZ6WFRvVFlDcHdsdmdId2NaaWtWK0QKYmZRTUVJbzhRRnBsaGtyblFtbVpsNDk4Q3cyRnlReitqYlNESlRhNHNQR2QrcDVvUTFHeHRoTGZxbTB0SVFDZwp5NnNrUi9UNEl2enZ0OXhCOGlBTmVyeklYQTcwQU5IUWdkYXNhMTlnaTJtcXhTbS9LU3dLWEpoTGdPT01ENW5xCmNOSEJBd2R0SEhxdDBIa3pxd0d3YWZqcHZVc2VSQnRVVWNRKzcxL3dIdlNKMm5xbkhhcXNaaVoxYjRvNHEyS0MKTXNSVEZ6Tmt3U2p3d05lYW9SVTZ4TXNqcGwxVFdhYTVLU0Z6bXpsb2VzZFBQdS9DZTRtSzJGMkpkQTJpVGxZaApUL1dDWUwxSU5UNjZVWDFyN1J4RnRnUU5TWnhTN3M3WlA2ZmxTQW42NHBWRnZleXlJaWRjeUh5Zjc4bzdjWDhDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVTGh1WDVROWtYVCs2Rmc1bApkQ05qYkhraytWMHdVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFyeDJqTzk1NFV0RjhWV1hnaTcwZWd3dDUwR3Y1TlZlM0RzYkQwaUlJczVqbwpuR2hYMFB6bjl2SDNyTjBCcmcxQ0cwOEhqSk5ka0dmNjA0UEoxMHI2R3Q4NVo3aWlKZTJ4QjcvcUdSbzR5MjBmCkVpZkpYTExsZEdvbFZIc2s5eDBMNGlQeVl1di9nNUl6NzlpdmFHR1FqOVNFWUxQZ1M2T3NtcUtnNitoY1IyWFcKSzZrdkpEYTNtYXJQcVlmRzFMUEFVbExWazNSRHJxamFVZ3F3MnhDV3UvZ1BmaXZiQUVsK0tCeVo1ZnNKM0N6RwpTVnFuRDNBMHJqblk1QTdMaXd6QUUyR1JHNVRrZy9nT0N1SEFKVkwxcEpaNVlEamRKdTNueDhyMEc1U0tSVHVHCjBSYlZKcEtkQmtpZ3BtaTZBMDRqckZKNWpFRm9WQW51WSt1ZFdxL0FYUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-kuberneteswatchtrigger
  failurePolicy: Fail
  name: vkuberneteswatchtrigger.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kuberneteswatchtriggers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU9pUTBlT0pRalBZYlA3cTFTTjNKdXN3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXdOekExTWpOYUZ3MHpNVEExTURVdwpOekExTWpOYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXZ6WFRvVFlDcHdsdmdId2NaaWtWK0QKYmZRTUVJbzhRRnBsaGtyblFtbVpsNDk4Q3cyRnlReitqYlNESlRhNHNQR2QrcDVvUTFHeHRoTGZxbTB0SVFDZwp5NnNrUi9UNEl2enZ0OXhCOGlBTmVyeklYQTcwQU5IUWdkYXNhMTlnaTJtcXhTbS9LU3dLWEpoTGdPT01ENW5xCmNOSEJBd2R0SEhxdDBIa3pxd0d3YWZqcHZVc2VSQnRVVWNRKzcxL3dIdlNKMm5xbkhhcXNaaVoxYjRvNHEyS0MKTXNSVEZ6Tmt3U2p3d05lYW9SVTZ4TXNqcGwxVFdhYTVLU0Z6bXpsb2VzZFBQdS9DZTRtSzJGMkpkQTJpVGxZaApUL1dDWUwxSU5UNjZVWDFyN1J4RnRnUU5TWnhTN3M3WlA2ZmxTQW42NHBWRnZleXlJaWRjeUh5Zjc4bzdjWDhDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVTGh1WDVROWtYVCs2Rmc1bApkQ05qYkhraytWMHdVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFyeDJqTzk1NFV0RjhWV1hnaTcwZWd3dDUwR3Y1TlZlM0RzYkQwaUlJczVqbwpuR2hYMFB6bjl2SDNyTjBCcmcxQ0cwOEhqSk5ka0dmNjA0UEoxMHI2R3Q4NVo3aWlKZTJ4QjcvcUdSbzR5MjBmCkVpZkpYTExsZEdvbFZIc2s5eDBMNGlQeVl1di9nNUl6NzlpdmFHR1FqOVNFWUxQZ1M2T3NtcUtnNitoY1IyWFcKSzZrdkpEYTNtYXJQcVlmRzFMUEFVbExWazNSRHJxamFVZ3F3MnhDV3UvZ1BmaXZiQUVsK0tCeVo1ZnNKM0N6RwpTVnFuRDNBMHJqblk1QTdMaXd6QUUyR1JHNVRrZy9nT0N1SEFKVkwxcEpaNVlEamRKdTNueDhyMEc1U0tSVHVHCjBSYlZKcEtkQmtpZ3BtaTZBMDRqckZKNWpFRm9WQW51WSt1ZFdxL0FYUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-messagequeuetrigger
  failurePolicy: Fail
  name: vmessagequeuetrigger.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - messagequeuetriggers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU9pUTBlT0pRalBZYlA3cTFTTjNKdXN3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXdOekExTWpOYUZ3MHpNVEExTURVdwpOekExTWpOYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXZ6WFRvVFlDcHdsdmdId2NaaWtWK0QKYmZRTUVJbzhRRnBsaGtyblFtbVpsNDk4Q3cyRnlReitqYlNESlRhNHNQR2QrcDVvUTFHeHRoTGZxbTB0SVFDZwp5NnNrUi9UNEl2enZ0OXhCOGlBTmVyeklYQTcwQU5IUWdkYXNhMTlnaTJtcXhTbS9LU3dLWEpoTGdPT01ENW5xCmNOSEJBd2R0SEhxdDBIa3pxd0d3YWZqcHZVc2VSQnRVVWNRKzcxL3dIdlNKMm5xbkhhcXNaaVoxYjRvNHEyS0MKTXNSVEZ6Tmt3U2p3d05lYW9SVTZ4TXNqcGwxVFdhYTVLU0Z6bXpsb2VzZFBQdS9DZTRtSzJGMkpkQTJpVGxZaApUL1dDWUwxSU5UNjZVWDFyN1J4RnRnUU5TWnhTN3M3WlA2ZmxTQW42NHBWRnZleXlJaWRjeUh5Zjc4bzdjWDhDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVTGh1WDVROWtYVCs2Rmc1bApkQ05qYkhraytWMHdVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFyeDJqTzk1NFV0RjhWV1hnaTcwZWd3dDUwR3Y1TlZlM0RzYkQwaUlJczVqbwpuR2hYMFB6bjl2SDNyTjBCcmcxQ0cwOEhqSk5ka0dmNjA0UEoxMHI2R3Q4NVo3aWlKZTJ4QjcvcUdSbzR5MjBmCkVpZkpYTExsZEdvbFZIc2s5eDBMNGlQeVl1di9nNUl6NzlpdmFHR1FqOVNFWUxQZ1M2T3NtcUtnNitoY1IyWFcKSzZrdkpEYTNtYXJQcVlmRzFMUEFVbExWazNSRHJxamFVZ3F3MnhDV3UvZ1BmaXZiQUVsK0tCeVo1ZnNKM0N6RwpTVnFuRDNBMHJqblk1QTdMaXd6QUUyR1JHNVRrZy9nT0N1SEFKVkwxcEpaNVlEamRKdTNueDhyMEc1U0tSVHVHCjBSYlZKcEtkQmtpZ3BtaTZBMDRqckZKNWpFRm9WQW51WSt1ZFdxL0FYUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-package
  failurePolicy: Fail
  name: vpackage.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - packages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU9pUTBlT0pRalBZYlA3cTFTTjNKdXN3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXdOekExTWpOYUZ3MHpNVEExTURVdwpOekExTWpOYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXZ6WFRvVFlDcHdsdmdId2NaaWtWK0QKYmZRTUVJbzhRRnBsaGtyblFtbVpsNDk4Q3cyRnlReitqYlNESlRhNHNQR2QrcDVvUTFHeHRoTGZxbTB0SVFDZwp5NnNrUi9UNEl2enZ0OXhCOGlBTmVyeklYQTcwQU5IUWdkYXNhMTlnaTJtcXhTbS9LU3dLWEpoTGdPT01ENW5xCmNOSEJBd2R0SEhxdDBIa3pxd0d3YWZqcHZVc2VSQnRVVWNRKzcxL3dIdlNKMm5xbkhhcXNaaVoxYjRvNHEyS0MKTXNSVEZ6Tmt3U2p3d05lYW9SVTZ4TXNqcGwxVFdhYTVLU0Z6bXpsb2VzZFBQdS9DZTRtSzJGMkpkQTJpVGxZaApUL1dDWUwxSU5UNjZVWDFyN1J4RnRnUU5TWnhTN3M3WlA2ZmxTQW42NHBWRnZleXlJaWRjeUh5Zjc4bzdjWDhDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVTGh1WDVROWtYVCs2Rmc1bApkQ05qYkhraytWMHdVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFyeDJqTzk1NFV0RjhWV1hnaTcwZWd3dDUwR3Y1TlZlM0RzYkQwaUlJczVqbwpuR2hYMFB6bjl2SDNyTjBCcmcxQ0cwOEhqSk5ka0dmNjA0UEoxMHI2R3Q4NVo3aWlKZTJ4QjcvcUdSbzR5MjBmCkVpZkpYTExsZEdvbFZIc2s5eDBMNGlQeVl1di9nNUl6NzlpdmFHR1FqOVNFWUxQZ1M2T3NtcUtnNitoY1IyWFcKSzZrdkpEYTNtYXJQcVlmRzFMUEFVbExWazNSRHJxamFVZ3F3MnhDV3UvZ1BmaXZiQUVsK0tCeVo1ZnNKM0N6RwpTVnFuRDNBMHJqblk1QTdMaXd6QUUyR1JHNVRrZy9nT0N1SEFKVkwxcEpaNVlEamRKdTNueDhyMEc1U0tSVHVHCjBSYlZKcEtkQmtpZ3BtaTZBMDRqckZKNWpFRm9WQW51WSt1ZFdxL0FYUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-timetrigger
  failurePolicy: Fail
  name: vtimetrigger.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - timetriggers
  sideEffects: None
