{
 "title": "Fission Admin dashboard",
 "tags": [ "" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Fission Internal Components Available replicas",
   "type": "timeseries",
   "description": "Shows the ready replicas of all internal fission components",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Pods" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{namespace=\"fission\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "title": "HTTP requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Http Requests served %",
   "type": "stat",
   "description": "Calculates the percentage of requests that returned a 200 response across all fission services.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{code=~\"20.*\"}[$__rate_interval])) / sum(rate(http_requests_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Http requests in flight",
   "type": "stat",
   "description": "The number of request fission is currently processing.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_in_flight{namespace=\"fission\"})"
    }
   ]
  },
  {
   "title": "Function Start Errors",
   "type": "stat",
   "description": "Number of errors faced by functions when called.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Errors" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_in_flight{namespace=\"fission\"})"
    }
   ]
  },
  {
   "title": "Function Errors",
   "type": "stat",
   "description": "Total number of errors faced by ",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Errors" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_in_flight{namespace=\"fission\"})"
    }
   ]
  },
  {
   "title": "Avg Fission overhead",
   "type": "stat",
   "description": "Average latency overhead for functions due to Fission.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fission_function_overhead_seconds_sum/fission_function_overhead_seconds_count)"
    }
   ]
  },
  {
   "title": "Mqt Subscriptions",
   "type": "stat",
   "description": "Message queue triggers",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fission_mqt_subscriptions" }
   ]
  },
  {
   "title": "Http requests in flight",
   "type": "timeseries",
   "description": "The number of request fission is currently processing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "http_requests_in_flight",
     "legendFormat": "{{container}} - {{namespace}} - {{path}}"
    }
   ]
  },
  {
   "title": "Cold Starts",
   "type": "timeseries",
   "description": "Cold starts for functions that ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(fission_function_cold_starts_total[5m])"
    }
   ]
  },
  {
   "title": "Function overhead",
   "type": "timeseries",
   "description": "Latency added to function calls due to fission overhead.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "fission_function_overhead_seconds",
     "legendFormat": "Function: {{function_name}} {{method}} {{code}} Percentile:{{quantile}}"
    }
   ]
  },
  { "title": "Archives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Fission Archive Total",
   "type": "stat",
   "description": "Total Number of archives present in the cluster",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fission_archives_total",
     "legendFormat": "Namespace: {{namespace}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Fission Archives Created/Deleted",
   "type": "timeseries",
   "description": "Changes in the number of fission archives",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(fission_archives_total[$__rate_interval])",
     "legendFormat": "Namespace: {{namespace}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Fission Archives Size",
   "type": "stat",
   "description": "Total size used by all archives",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fission_archive_memory_bytes",
     "legendFormat": "Namespace: {{namespace}} Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Fission Archives Size",
   "type": "timeseries",
   "description": "Size used by fission archives",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(fission_archive_memory_bytes) by (pod,namespacem,service)",
     "legendFormat": "Namespace: {{namespace}} Pod: {{pod}}"
    }
   ]
  }
 ]
}