apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: fission-validating-webhooks
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1LZ0F3SUJBZ0lRSmlQeThVYTRURnEyUCsyaVE1RGNwVEFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwbWFYTnphVzl1TFdOaE1CNFhEVEkyTURVeE56RXpNVGd5TlZvWERUTXhNRFV4TmpFegpNVGd5TlZvd0pqRWtNQ0lHQTFVRUF4TWJkMlZpYUc5dmF5MXpaWEoyYVdObExtWnBjM05wYjI0dWMzWmpNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFva2lvQkw1QTRnVnlGM0JZVDB5MWp0bWsKem9WeVl4L2pPNkhNZEkxSS9UYml5Y3ppZGRLMzVwL3ptdFZ6aTdTa2dZZHZWbnpJZnRRUFl1cHJOMXBFeDM4WQpxWGh3QTViNTFYUzJVN2hseUdLRk1penFSWndVN1p4Qlp5ZlR2QjNzL3NjSzRyYWx5OUI1cnZXcWNheHhzV09MCkZqeVpUTk5kQmZ6UzM3LzMzYkxwSHJML00vNnZZU2lGNXdwK2pvczNpUXJVZmhoN0k5OTUvOGhuWGVaRUtGdWkKN2p5VWVhSHRwNWsvRmFWUTJ4STN3UU1kczQ4UWxXQUNzUUlyNGJ6T0ZnUUxNck5VYndJNys1cjQrRGNFVzJOVQpkTXRtUG5DdEdHSS9LVWRKNmx5NzJ2dU1OV1RONGluc1Nrd1pNOGZwVVN1YWRhY3hzeHdwYzNRdVAxT1laUUlECkFRQUJvNEcwTUlHeE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlRLOE9CaTNEQXluRWJxenNPYwo2Q0JBZHd2V1h6QlJCZ05WSFJFRVNqQklnaHQzWldKb2IyOXJMWE5sY25acFkyVXVabWx6YzJsdmJpNXpkbU9DCktYZGxZbWh2YjJzdGMyVnlkbWxqWlM1bWFYTnphVzl1TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQmVxTU13QmErN2VjUy9IZXNWcnFGK2N6WSsxczlESFZzRjB1OTVid3RYQ1VTcgpIa2h3d3piTVBnRnpjT0p4T0g1ZFkyT284NSsycytNTWo5QUZPdERtRTVhK29OL0x2RHlwam9oNmRpSHFJUVlyCmdWRUZFZlZvT3VWOGlRUVZxVlJBZk1KRG5aYnhudkF1VTRJdlNSNWIrNno2MHpKWHN3Rmh4TkpDTUZkVW1HWUQKQW43Uk1aRXEwV3NjN3VzVmpmQXNJeUgxdEs4T3hkeHV2Nk1hYzNCNlJqWFI3YWxHMHBjL3VRcTBOSTFLWVU1NQpqSld2NkpuN09nZUt3Y2ZUakpWRWdvb2NZQU1xcFhSTVhLUXUzeXhFSW9HR1VvVHdTMXNwM3dRc3BsS0VwemZSCnlLektDTFVoZHJCOUxoa0srRk15Z0dSZWMyWjJac09URzlhVlRjOHAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-environment
  failurePolicy: Fail
  name: venvironment.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - environments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1LZ0F3SUJBZ0lRSmlQeThVYTRURnEyUCsyaVE1RGNwVEFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwbWFYTnphVzl1TFdOaE1CNFhEVEkyTURVeE56RXpNVGd5TlZvWERUTXhNRFV4TmpFegpNVGd5TlZvd0pqRWtNQ0lHQTFVRUF4TWJkMlZpYUc5dmF5MXpaWEoyYVdObExtWnBjM05wYjI0dWMzWmpNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFva2lvQkw1QTRnVnlGM0JZVDB5MWp0bWsKem9WeVl4L2pPNkhNZEkxSS9UYml5Y3ppZGRLMzVwL3ptdFZ6aTdTa2dZZHZWbnpJZnRRUFl1cHJOMXBFeDM4WQpxWGh3QTViNTFYUzJVN2hseUdLRk1penFSWndVN1p4Qlp5ZlR2QjNzL3NjSzRyYWx5OUI1cnZXcWNheHhzV09MCkZqeVpUTk5kQmZ6UzM3LzMzYkxwSHJML00vNnZZU2lGNXdwK2pvczNpUXJVZmhoN0k5OTUvOGhuWGVaRUtGdWkKN2p5VWVhSHRwNWsvRmFWUTJ4STN3UU1kczQ4UWxXQUNzUUlyNGJ6T0ZnUUxNck5VYndJNys1cjQrRGNFVzJOVQpkTXRtUG5DdEdHSS9LVWRKNmx5NzJ2dU1OV1RONGluc1Nrd1pNOGZwVVN1YWRhY3hzeHdwYzNRdVAxT1laUUlECkFRQUJvNEcwTUlHeE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlRLOE9CaTNEQXluRWJxenNPYwo2Q0JBZHd2V1h6QlJCZ05WSFJFRVNqQklnaHQzWldKb2IyOXJMWE5sY25acFkyVXVabWx6YzJsdmJpNXpkbU9DCktYZGxZbWh2YjJzdGMyVnlkbWxqWlM1bWFYTnphVzl1TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQmVxTU13QmErN2VjUy9IZXNWcnFGK2N6WSsxczlESFZzRjB1OTVid3RYQ1VTcgpIa2h3d3piTVBnRnpjT0p4T0g1ZFkyT284NSsycytNTWo5QUZPdERtRTVhK29OL0x2RHlwam9oNmRpSHFJUVlyCmdWRUZFZlZvT3VWOGlRUVZxVlJBZk1KRG5aYnhudkF1VTRJdlNSNWIrNno2MHpKWHN3Rmh4TkpDTUZkVW1HWUQKQW43Uk1aRXEwV3NjN3VzVmpmQXNJeUgxdEs4T3hkeHV2Nk1hYzNCNlJqWFI3YWxHMHBjL3VRcTBOSTFLWVU1NQpqSld2NkpuN09nZUt3Y2ZUakpWRWdvb2NZQU1xcFhSTVhLUXUzeXhFSW9HR1VvVHdTMXNwM3dRc3BsS0VwemZSCnlLektDTFVoZHJCOUxoa0srRk15Z0dSZWMyWjJac09URzlhVlRjOHAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-function
  failurePolicy: Fail
  name: vfunction.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - functions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1LZ0F3SUJBZ0lRSmlQeThVYTRURnEyUCsyaVE1RGNwVEFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwbWFYTnphVzl1TFdOaE1CNFhEVEkyTURVeE56RXpNVGd5TlZvWERUTXhNRFV4TmpFegpNVGd5TlZvd0pqRWtNQ0lHQTFVRUF4TWJkMlZpYUc5dmF5MXpaWEoyYVdObExtWnBjM05wYjI0dWMzWmpNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFva2lvQkw1QTRnVnlGM0JZVDB5MWp0bWsKem9WeVl4L2pPNkhNZEkxSS9UYml5Y3ppZGRLMzVwL3ptdFZ6aTdTa2dZZHZWbnpJZnRRUFl1cHJOMXBFeDM4WQpxWGh3QTViNTFYUzJVN2hseUdLRk1penFSWndVN1p4Qlp5ZlR2QjNzL3NjSzRyYWx5OUI1cnZXcWNheHhzV09MCkZqeVpUTk5kQmZ6UzM3LzMzYkxwSHJML00vNnZZU2lGNXdwK2pvczNpUXJVZmhoN0k5OTUvOGhuWGVaRUtGdWkKN2p5VWVhSHRwNWsvRmFWUTJ4STN3UU1kczQ4UWxXQUNzUUlyNGJ6T0ZnUUxNck5VYndJNys1cjQrRGNFVzJOVQpkTXRtUG5DdEdHSS9LVWRKNmx5NzJ2dU1OV1RONGluc1Nrd1pNOGZwVVN1YWRhY3hzeHdwYzNRdVAxT1laUUlECkFRQUJvNEcwTUlHeE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlRLOE9CaTNEQXluRWJxenNPYwo2Q0JBZHd2V1h6QlJCZ05WSFJFRVNqQklnaHQzWldKb2IyOXJMWE5sY25acFkyVXVabWx6YzJsdmJpNXpkbU9DCktYZGxZbWh2YjJzdGMyVnlkbWxqWlM1bWFYTnphVzl1TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQmVxTU13QmErN2VjUy9IZXNWcnFGK2N6WSsxczlESFZzRjB1OTVid3RYQ1VTcgpIa2h3d3piTVBnRnpjT0p4T0g1ZFkyT284NSsycytNTWo5QUZPdERtRTVhK29OL0x2RHlwam9oNmRpSHFJUVlyCmdWRUZFZlZvT3VWOGlRUVZxVlJBZk1KRG5aYnhudkF1VTRJdlNSNWIrNno2MHpKWHN3Rmh4TkpDTUZkVW1HWUQKQW43Uk1aRXEwV3NjN3VzVmpmQXNJeUgxdEs4T3hkeHV2Nk1hYzNCNlJqWFI3YWxHMHBjL3VRcTBOSTFLWVU1NQpqSld2NkpuN09nZUt3Y2ZUakpWRWdvb2NZQU1xcFhSTVhLUXUzeXhFSW9HR1VvVHdTMXNwM3dRc3BsS0VwemZSCnlLektDTFVoZHJCOUxoa0srRk15Z0dSZWMyWjJac09URzlhVlRjOHAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-httptrigger
  failurePolicy: Fail
  name: vhttptrigger.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - httptriggers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1LZ0F3SUJBZ0lRSmlQeThVYTRURnEyUCsyaVE1RGNwVEFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwbWFYTnphVzl1TFdOaE1CNFhEVEkyTURVeE56RXpNVGd5TlZvWERUTXhNRFV4TmpFegpNVGd5TlZvd0pqRWtNQ0lHQTFVRUF4TWJkMlZpYUc5dmF5MXpaWEoyYVdObExtWnBjM05wYjI0dWMzWmpNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFva2lvQkw1QTRnVnlGM0JZVDB5MWp0bWsKem9WeVl4L2pPNkhNZEkxSS9UYml5Y3ppZGRLMzVwL3ptdFZ6aTdTa2dZZHZWbnpJZnRRUFl1cHJOMXBFeDM4WQpxWGh3QTViNTFYUzJVN2hseUdLRk1penFSWndVN1p4Qlp5ZlR2QjNzL3NjSzRyYWx5OUI1cnZXcWNheHhzV09MCkZqeVpUTk5kQmZ6UzM3LzMzYkxwSHJML00vNnZZU2lGNXdwK2pvczNpUXJVZmhoN0k5OTUvOGhuWGVaRUtGdWkKN2p5VWVhSHRwNWsvRmFWUTJ4STN3UU1kczQ4UWxXQUNzUUlyNGJ6T0ZnUUxNck5VYndJNys1cjQrRGNFVzJOVQpkTXRtUG5DdEdHSS9LVWRKNmx5NzJ2dU1OV1RONGluc1Nrd1pNOGZwVVN1YWRhY3hzeHdwYzNRdVAxT1laUUlECkFRQUJvNEcwTUlHeE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlRLOE9CaTNEQXluRWJxenNPYwo2Q0JBZHd2V1h6QlJCZ05WSFJFRVNqQklnaHQzWldKb2IyOXJMWE5sY25acFkyVXVabWx6YzJsdmJpNXpkbU9DCktYZGxZbWh2YjJzdGMyVnlkbWxqWlM1bWFYTnphVzl1TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQmVxTU13QmErN2VjUy9IZXNWcnFGK2N6WSsxczlESFZzRjB1OTVid3RYQ1VTcgpIa2h3d3piTVBnRnpjT0p4T0g1ZFkyT284NSsycytNTWo5QUZPdERtRTVhK29OL0x2RHlwam9oNmRpSHFJUVlyCmdWRUZFZlZvT3VWOGlRUVZxVlJBZk1KRG5aYnhudkF1VTRJdlNSNWIrNno2MHpKWHN3Rmh4TkpDTUZkVW1HWUQKQW43Uk1aRXEwV3NjN3VzVmpmQXNJeUgxdEs4T3hkeHV2Nk1hYzNCNlJqWFI3YWxHMHBjL3VRcTBOSTFLWVU1NQpqSld2NkpuN09nZUt3Y2ZUakpWRWdvb2NZQU1xcFhSTVhLUXUzeXhFSW9HR1VvVHdTMXNwM3dRc3BsS0VwemZSCnlLektDTFVoZHJCOUxoa0srRk15Z0dSZWMyWjJac09URzlhVlRjOHAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-kuberneteswatchtrigger
  failurePolicy: Fail
  name: vkuberneteswatchtrigger.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kuberneteswatchtriggers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1LZ0F3SUJBZ0lRSmlQeThVYTRURnEyUCsyaVE1RGNwVEFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwbWFYTnphVzl1TFdOaE1CNFhEVEkyTURVeE56RXpNVGd5TlZvWERUTXhNRFV4TmpFegpNVGd5TlZvd0pqRWtNQ0lHQTFVRUF4TWJkMlZpYUc5dmF5MXpaWEoyYVdObExtWnBjM05wYjI0dWMzWmpNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFva2lvQkw1QTRnVnlGM0JZVDB5MWp0bWsKem9WeVl4L2pPNkhNZEkxSS9UYml5Y3ppZGRLMzVwL3ptdFZ6aTdTa2dZZHZWbnpJZnRRUFl1cHJOMXBFeDM4WQpxWGh3QTViNTFYUzJVN2hseUdLRk1penFSWndVN1p4Qlp5ZlR2QjNzL3NjSzRyYWx5OUI1cnZXcWNheHhzV09MCkZqeVpUTk5kQmZ6UzM3LzMzYkxwSHJML00vNnZZU2lGNXdwK2pvczNpUXJVZmhoN0k5OTUvOGhuWGVaRUtGdWkKN2p5VWVhSHRwNWsvRmFWUTJ4STN3UU1kczQ4UWxXQUNzUUlyNGJ6T0ZnUUxNck5VYndJNys1cjQrRGNFVzJOVQpkTXRtUG5DdEdHSS9LVWRKNmx5NzJ2dU1OV1RONGluc1Nrd1pNOGZwVVN1YWRhY3hzeHdwYzNRdVAxT1laUUlECkFRQUJvNEcwTUlHeE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlRLOE9CaTNEQXluRWJxenNPYwo2Q0JBZHd2V1h6QlJCZ05WSFJFRVNqQklnaHQzWldKb2IyOXJMWE5sY25acFkyVXVabWx6YzJsdmJpNXpkbU9DCktYZGxZbWh2YjJzdGMyVnlkbWxqWlM1bWFYTnphVzl1TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQmVxTU13QmErN2VjUy9IZXNWcnFGK2N6WSsxczlESFZzRjB1OTVid3RYQ1VTcgpIa2h3d3piTVBnRnpjT0p4T0g1ZFkyT284NSsycytNTWo5QUZPdERtRTVhK29OL0x2RHlwam9oNmRpSHFJUVlyCmdWRUZFZlZvT3VWOGlRUVZxVlJBZk1KRG5aYnhudkF1VTRJdlNSNWIrNno2MHpKWHN3Rmh4TkpDTUZkVW1HWUQKQW43Uk1aRXEwV3NjN3VzVmpmQXNJeUgxdEs4T3hkeHV2Nk1hYzNCNlJqWFI3YWxHMHBjL3VRcTBOSTFLWVU1NQpqSld2NkpuN09nZUt3Y2ZUakpWRWdvb2NZQU1xcFhSTVhLUXUzeXhFSW9HR1VvVHdTMXNwM3dRc3BsS0VwemZSCnlLektDTFVoZHJCOUxoa0srRk15Z0dSZWMyWjJac09URzlhVlRjOHAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-messagequeuetrigger
  failurePolicy: Fail
  name: vmessagequeuetrigger.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - messagequeuetriggers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1LZ0F3SUJBZ0lRSmlQeThVYTRURnEyUCsyaVE1RGNwVEFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwbWFYTnphVzl1TFdOaE1CNFhEVEkyTURVeE56RXpNVGd5TlZvWERUTXhNRFV4TmpFegpNVGd5TlZvd0pqRWtNQ0lHQTFVRUF4TWJkMlZpYUc5dmF5MXpaWEoyYVdObExtWnBjM05wYjI0dWMzWmpNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFva2lvQkw1QTRnVnlGM0JZVDB5MWp0bWsKem9WeVl4L2pPNkhNZEkxSS9UYml5Y3ppZGRLMzVwL3ptdFZ6aTdTa2dZZHZWbnpJZnRRUFl1cHJOMXBFeDM4WQpxWGh3QTViNTFYUzJVN2hseUdLRk1penFSWndVN1p4Qlp5ZlR2QjNzL3NjSzRyYWx5OUI1cnZXcWNheHhzV09MCkZqeVpUTk5kQmZ6UzM3LzMzYkxwSHJML00vNnZZU2lGNXdwK2pvczNpUXJVZmhoN0k5OTUvOGhuWGVaRUtGdWkKN2p5VWVhSHRwNWsvRmFWUTJ4STN3UU1kczQ4UWxXQUNzUUlyNGJ6T0ZnUUxNck5VYndJNys1cjQrRGNFVzJOVQpkTXRtUG5DdEdHSS9LVWRKNmx5NzJ2dU1OV1RONGluc1Nrd1pNOGZwVVN1YWRhY3hzeHdwYzNRdVAxT1laUUlECkFRQUJvNEcwTUlHeE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlRLOE9CaTNEQXluRWJxenNPYwo2Q0JBZHd2V1h6QlJCZ05WSFJFRVNqQklnaHQzWldKb2IyOXJMWE5sY25acFkyVXVabWx6YzJsdmJpNXpkbU9DCktYZGxZbWh2YjJzdGMyVnlkbWxqWlM1bWFYTnphVzl1TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQmVxTU13QmErN2VjUy9IZXNWcnFGK2N6WSsxczlESFZzRjB1OTVid3RYQ1VTcgpIa2h3d3piTVBnRnpjT0p4T0g1ZFkyT284NSsycytNTWo5QUZPdERtRTVhK29OL0x2RHlwam9oNmRpSHFJUVlyCmdWRUZFZlZvT3VWOGlRUVZxVlJBZk1KRG5aYnhudkF1VTRJdlNSNWIrNno2MHpKWHN3Rmh4TkpDTUZkVW1HWUQKQW43Uk1aRXEwV3NjN3VzVmpmQXNJeUgxdEs4T3hkeHV2Nk1hYzNCNlJqWFI3YWxHMHBjL3VRcTBOSTFLWVU1NQpqSld2NkpuN09nZUt3Y2ZUakpWRWdvb2NZQU1xcFhSTVhLUXUzeXhFSW9HR1VvVHdTMXNwM3dRc3BsS0VwemZSCnlLektDTFVoZHJCOUxoa0srRk15Z0dSZWMyWjJac09URzlhVlRjOHAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-package
  failurePolicy: Fail
  name: vpackage.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - packages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1LZ0F3SUJBZ0lRSmlQeThVYTRURnEyUCsyaVE1RGNwVEFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwbWFYTnphVzl1TFdOaE1CNFhEVEkyTURVeE56RXpNVGd5TlZvWERUTXhNRFV4TmpFegpNVGd5TlZvd0pqRWtNQ0lHQTFVRUF4TWJkMlZpYUc5dmF5MXpaWEoyYVdObExtWnBjM05wYjI0dWMzWmpNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFva2lvQkw1QTRnVnlGM0JZVDB5MWp0bWsKem9WeVl4L2pPNkhNZEkxSS9UYml5Y3ppZGRLMzVwL3ptdFZ6aTdTa2dZZHZWbnpJZnRRUFl1cHJOMXBFeDM4WQpxWGh3QTViNTFYUzJVN2hseUdLRk1penFSWndVN1p4Qlp5ZlR2QjNzL3NjSzRyYWx5OUI1cnZXcWNheHhzV09MCkZqeVpUTk5kQmZ6UzM3LzMzYkxwSHJML00vNnZZU2lGNXdwK2pvczNpUXJVZmhoN0k5OTUvOGhuWGVaRUtGdWkKN2p5VWVhSHRwNWsvRmFWUTJ4STN3UU1kczQ4UWxXQUNzUUlyNGJ6T0ZnUUxNck5VYndJNys1cjQrRGNFVzJOVQpkTXRtUG5DdEdHSS9LVWRKNmx5NzJ2dU1OV1RONGluc1Nrd1pNOGZwVVN1YWRhY3hzeHdwYzNRdVAxT1laUUlECkFRQUJvNEcwTUlHeE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlRLOE9CaTNEQXluRWJxenNPYwo2Q0JBZHd2V1h6QlJCZ05WSFJFRVNqQklnaHQzWldKb2IyOXJMWE5sY25acFkyVXVabWx6YzJsdmJpNXpkbU9DCktYZGxZbWh2YjJzdGMyVnlkbWxqWlM1bWFYTnphVzl1TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQmVxTU13QmErN2VjUy9IZXNWcnFGK2N6WSsxczlESFZzRjB1OTVid3RYQ1VTcgpIa2h3d3piTVBnRnpjT0p4T0g1ZFkyT284NSsycytNTWo5QUZPdERtRTVhK29OL0x2RHlwam9oNmRpSHFJUVlyCmdWRUZFZlZvT3VWOGlRUVZxVlJBZk1KRG5aYnhudkF1VTRJdlNSNWIrNno2MHpKWHN3Rmh4TkpDTUZkVW1HWUQKQW43Uk1aRXEwV3NjN3VzVmpmQXNJeUgxdEs4T3hkeHV2Nk1hYzNCNlJqWFI3YWxHMHBjL3VRcTBOSTFLWVU1NQpqSld2NkpuN09nZUt3Y2ZUakpWRWdvb2NZQU1xcFhSTVhLUXUzeXhFSW9HR1VvVHdTMXNwM3dRc3BsS0VwemZSCnlLektDTFVoZHJCOUxoa0srRk15Z0dSZWMyWjJac09URzlhVlRjOHAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-timetrigger
  failurePolicy: Fail
  name: vtimetrigger.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - timetriggers
  sideEffects: None
