apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: fission-mutating-webhooks
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQUtNc282OUN5OWhsdmpIVjZBRnZVT3d3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1UY3dNakkyTVRsYUZ3MHpNVEExTVRZdwpNakkyTVRsYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFlVSmtIRkttOURscHIxQjJTeE9pMHUKZlJ2Y0tHdWU5QmZ0SVladG9PMVVIU0ZwdkRlZ2FJRHJXeUJlVDgvLzh3eU5RSlZPSGU3V3g1dnRVVSs5WGw5NwpNME0ycDhmZDhoM3FXUHhCNGdBYytvclM4UnhRQkI0L1p6b3hkU1ZRVzFSVTZrbU5IM1VsYTJsYUJNTkpsbnFSCkVxVnQvUFI1ak83N1RNU0pLcWd2MlFlWU1HRC9xZm1tbUxuYWRSYTRhd2JhOGVIS3FCaGtJcTA3enkxc0pGblQKbjlBZXJHU3lSVG5BL2R0eTlkL1oyQTNWZXhxcFg1UXQ5eHRGWE9SL00wL0lRRGNud3c0ZGF6aE9FVVBrMkRwRwpiOEM2RWQxWGN3anlyY2FkbDBmcWFHTjNKeElWbHRlY0FBUHJsa2pjcGxLQlYyUHJmR3NHS2NlUFRIN2plSzhDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVek5VUEx6QWFWNjVvR0ZPUApKUjZVbklFODVrb3dVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFpakE2UE5kd3R0dWg4NG1pRHZzN0FYamFIVzQ3b1VpSEc3ck9HbElVQVpudQpYT0dCTTUvanEwQVNLWHZCemRWUktKQzMvZzErdXBPeHF1SGxNTkZkYWxWOHdCUmI1ZGIvUUdOVlFtMHBrK3BnCm8zWHlpQkJLMFZQNFd3cHhycEZiK0t1dlVUbXJsWVNoblFzVW9mMjMwVkJPSC9ac3dLNWVlOUxpblpTS01tWWUKNWlrN3N6OU5KQytleFBpUUhrOFYwUlZBd1RFL3k2MUF3WHQ1VEpya2RFWGorSjk5Q0Q1STJLYU12NU5TYTRDSQovSGhOZDYvZjduN3E3ekpuKytoN2dGeUZOUktIRXN3dXhobzF0Um81MDRTZ2hLMTVqNWhqYXBKMURFVy9YR0JXCjRCbDFPdVZUWlI2dk9yMkRrRERIVUlzVmdmM0x6b3JjakhJZXNOR3g2Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /mutate-fission-io-v1-package
  failurePolicy: Fail
  name: mpackage.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - packages
  sideEffects: None
