apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: fission-mutating-webhooks
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQUw3Rm9BK3YyTnA0NGV4Rit5SUFVRGd3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1UY3hNakEwTURKYUZ3MHpNVEExTVRZeApNakEwTURKYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTk5sKzdwbmM1MWhpKyttU3NneFNqRnoKaWtZeEJnZEMyVUJGNStLOHNubzlOOHd1d2V0QzUwU1ZTNHBFbkpnMTU2UFY1ZmlEV0JBYiszT1NRM1RPOEVudApXeDhZZDdFNjEzRVR2SVlabWkzUUZaSzdIbnFJQWk2VFNCOUtiTmpUcCs4MTBHbG5oQ0F0NGUxMnl3cUIvcDFDCk42V3cvZStJM1h4WkNoZm92QXZhTW42MS9NTm5RZElhcUcyd2FyRlh2d2FVZ3B1NlR6SkpHL05iUTQ2cmRtQkEKRUtQOHA0dm5hS0RhK3l0UkJKNE5DL1NsY3AvcU9uV2RiY3lrTnVlUFpLWnMvTGh5dEMzWTV3eTJrSk9nNFNvZQphWi9ybTI0aXptZDlmRlRwaGNudFpMOWVCZVVvVm5EN282Y1I1Um9aeVVGR20yZzlxbUNKRmU0eGdVb0UyN3NDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVaGVWVk9pcHBWczhPN2h0OAp1dkZvS2FhTGIrQXdVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFrK29DYk05UEtlOTRlejkrelZRT1RtY0FVYlkxOVNJd2FYNUM3cURjeU1DNQovZ1BsOXhpcmR1Wk9aUDFrUnVOTWwwalAzZlMyQ0ZEUERxNnA1L09xMFFXcEdydCs5YUZhS1dNUkovWGpKT3hQCjdLbVZZaGZzNmtmTy9Gd2M3cTBVUEN6RmJZMW1taldRb25KeDh2dTdGZ0NLVGZmRzh6U2FFM1Fjak1wYlpmdVMKN2RLeWswdXNDakVEWFlWT3grYWpMbVMwaUlWMmF1R09QMlZ2RHRnR1E5M3kzVE93dTF5K3NNYUZna2w5MTBHVApicE1NV3Z0MDRtQXQ5SW9Ed2ZMWjJTa3ljT2tuZWpibkVWRTRFRkRpM0xQVDU0N3lIYjVDZHBvOUpXUXQrNlY2ClllNGFqZVAzY294REpGd09wZkpjNzFHM3NvUmFmWU1UWXlnbHVSRGlhdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /mutate-fission-io-v1-package
  failurePolicy: Fail
  name: mpackage.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - packages
  sideEffects: None
