apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: fission-mutating-webhooks
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlakNDQW1LZ0F3SUJBZ0lRREZwa0NaSVMvNUZ5TVlaWXZNRGc0ekFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwbWFYTnphVzl1TFdOaE1CNFhEVEkyTURVeE56RXlNRFF5TUZvWERUTXhNRFV4TmpFeQpNRFF5TUZvd0pqRWtNQ0lHQTFVRUF4TWJkMlZpYUc5dmF5MXpaWEoyYVdObExtWnBjM05wYjI0dWMzWmpNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE1VDB4bXB1Z05zdm1KbUpIM0Fpa2xWTUUKWUd4ZGZ2SVI3VmhtMDkxL2R4VDlrSExad2MyNWNmZVhlWHhyMEMzMjBpK1l2d1dEWnF6L3d0WnFwVUExOWkyWgpZN2lpZ21yeElUemlVMDVEUXJVeTBjOGtmb1VOTHVDaDVjLys0WHgvL0hjb0w1OHNqTjh2OHhKbGxycEdXa054CjRZZDNzNlZmVUVERFVvRGFOWXRiQmt0ejFQLzdRbXFOZXVvZDUxeWhVWGNVUTR5WHlJZFlPQ05ld01VdU9hamYKS01wMlpqTEIzMmdKdnREaWFEbEdHdUEzVGxGWVQ1N2RTSmpENTZzc0V0N0NTNll4d283dGtkY1VnR3FiUTZ3bAp2YW1ucFRuaWM5S2oybm02Zk9FenVZZnlNOUhjeU14WEVFV0p3aWcxQ09RSlJTSW5HNFFuZHdwNEZnZFFtd0lECkFRQUJvNEcwTUlHeE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlNXb1BWYlcvcHZzcjlNdmxpQQpkLzRuRXBBcWtEQlJCZ05WSFJFRVNqQklnaHQzWldKb2IyOXJMWE5sY25acFkyVXVabWx6YzJsdmJpNXpkbU9DCktYZGxZbWh2YjJzdGMyVnlkbWxqWlM1bWFYTnphVzl1TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQW1Zclk2Q0dFLzVyZVNoRFVRSDRaN3UwS0kwcTQwMWtDMU1GVkNwWWNrMjN4eAoyQXhnOTRNSERTNmI5S0hBRENZaGRuSFBHaGYzdnlrcHREb3dOTTByaXdnTmhxdE9YVy9UQ0tpcmgvN01YVjB4CjlnemJvejl1WFdJSzFPQkRRSEFqa2I2QUVtNVNTV3JlYmQxOWZYZFVLRGJOTUZMWHVUUlJrY0VjYVNOQmZLK0IKL3RDUkNkVUhHZ0xHaFc3WUg2ZlZkUzBJQmVocmdlOUJTVnk1UlZTQklsRVpzQnJNbXZRcm1zZHZudjMvR3ZwVAo1bkxmQ1ZMV2JDNnZjdkVFNkp4YytWU3FHRmZNa1l6ZlFTdDE4TzNRR0tpSG1SSHlDVWczcUdSamJmb2NvK0xZCjA1NGhqSVdkZkRQbVlTMnpFNXYxNzdLVHNnYWFPMk4wZWMrS0VCNmsKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: webhook-service
      namespace: fission
      path: /mutate-fission-io-v1-package
  failurePolicy: Fail
  name: mpackage.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - packages
  sideEffects: None
