apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: fission-validating-webhooks
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU8rdFRRMTJnWDM0MEpxb3ZIVkc3WG93RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXhORFV6TURKYUZ3MHpNVEExTURVeApORFV6TURKYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTU4zdkI4cXQ1b0xuT0tBQTdvc2xYTjUKREtmS3A5K1dCbkVPc0hYcGJVSXF0VncvSHdscWgrMkZnZmR2OGt2TDR3c3MweisyMjhmTHArblFRSnFzV3VGWgo5eGpFZ0d3bDBJWUNhVDdrc1RxY21jdU5DemxxZG8zN3o2MUxJV3RtbVQyRFB6MjlNZ3hwUkozdStxb2ViV3lECk40NEUzQ0ZYaUJsOUJpMjFXM3ZvY0NrN1FMbkM1ZFlhczlhVWpxdWNGaXhPTDBlMmR5WnBmMHl2RUJTMGtuWHYKcjFjdkxnUGpCcUU5OGlZY0dJanU4OWl4UXg1YjRlWFVPeHlhQjVCN0p2Mml3dmJGU0ZpR3VxdUtURXBHT0dLegoyOTArT3Fpd2ZZamd4TlVHZkhmR0Y5S1o4MlF1cXFib3dhVnZiNnA3Zy9lNlRZK3ZMcWc1cTFKQVhWRG50ZzBDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVMFZPUXYvSzduWGlHb3hRbApJTDE0NVFwSDRLa3dVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFuMi96Wlh5ZGgyRzBCbnRqWHFhTWtaV0hYV3p1UmFHRVZTbXB5NjVhcC94Wgpud1NTd3QxQVllZlFLY1dPZmpLNmova1ZuNkoyY1VHQkZJdm9ha0FHMGZEczVEcVUvbUk1VTl5dzBQVE83amxYCjU0cytFTWROVU43QTUvK1IyTDE2Qmp2U05FVTdHUXZMd29PYjlYaGs2bGZ5MS95ZjJSNUpILzZISXZlNXFJNnQKMW5EQnpkdENtcVRLSFhsajZKdkp0NDlMVVhlUDhsSGRlYkFuc00ydk4xU1hiV3NHVnZDSUtDbVdrWGZuNTJkdwpqbDZMS2FzQmFxSXR1bENydVl1b3JBT0xzMXNwWiswMVliKzFqV1NSMVFNSStBamJiaS9RSnlJMVZua2NnOGk0CmY0WElNNUl2V21hYXJsSUJMRTZHQWJITTJ2MlZsV2J0aFBZeW4yd3dnZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-environment
  failurePolicy: Fail
  name: venvironment.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - environments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU8rdFRRMTJnWDM0MEpxb3ZIVkc3WG93RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXhORFV6TURKYUZ3MHpNVEExTURVeApORFV6TURKYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTU4zdkI4cXQ1b0xuT0tBQTdvc2xYTjUKREtmS3A5K1dCbkVPc0hYcGJVSXF0VncvSHdscWgrMkZnZmR2OGt2TDR3c3MweisyMjhmTHArblFRSnFzV3VGWgo5eGpFZ0d3bDBJWUNhVDdrc1RxY21jdU5DemxxZG8zN3o2MUxJV3RtbVQyRFB6MjlNZ3hwUkozdStxb2ViV3lECk40NEUzQ0ZYaUJsOUJpMjFXM3ZvY0NrN1FMbkM1ZFlhczlhVWpxdWNGaXhPTDBlMmR5WnBmMHl2RUJTMGtuWHYKcjFjdkxnUGpCcUU5OGlZY0dJanU4OWl4UXg1YjRlWFVPeHlhQjVCN0p2Mml3dmJGU0ZpR3VxdUtURXBHT0dLegoyOTArT3Fpd2ZZamd4TlVHZkhmR0Y5S1o4MlF1cXFib3dhVnZiNnA3Zy9lNlRZK3ZMcWc1cTFKQVhWRG50ZzBDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVMFZPUXYvSzduWGlHb3hRbApJTDE0NVFwSDRLa3dVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFuMi96Wlh5ZGgyRzBCbnRqWHFhTWtaV0hYV3p1UmFHRVZTbXB5NjVhcC94Wgpud1NTd3QxQVllZlFLY1dPZmpLNmova1ZuNkoyY1VHQkZJdm9ha0FHMGZEczVEcVUvbUk1VTl5dzBQVE83amxYCjU0cytFTWROVU43QTUvK1IyTDE2Qmp2U05FVTdHUXZMd29PYjlYaGs2bGZ5MS95ZjJSNUpILzZISXZlNXFJNnQKMW5EQnpkdENtcVRLSFhsajZKdkp0NDlMVVhlUDhsSGRlYkFuc00ydk4xU1hiV3NHVnZDSUtDbVdrWGZuNTJkdwpqbDZMS2FzQmFxSXR1bENydVl1b3JBT0xzMXNwWiswMVliKzFqV1NSMVFNSStBamJiaS9RSnlJMVZua2NnOGk0CmY0WElNNUl2V21hYXJsSUJMRTZHQWJITTJ2MlZsV2J0aFBZeW4yd3dnZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-function
  failurePolicy: Fail
  name: vfunction.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - functions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU8rdFRRMTJnWDM0MEpxb3ZIVkc3WG93RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXhORFV6TURKYUZ3MHpNVEExTURVeApORFV6TURKYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTU4zdkI4cXQ1b0xuT0tBQTdvc2xYTjUKREtmS3A5K1dCbkVPc0hYcGJVSXF0VncvSHdscWgrMkZnZmR2OGt2TDR3c3MweisyMjhmTHArblFRSnFzV3VGWgo5eGpFZ0d3bDBJWUNhVDdrc1RxY21jdU5DemxxZG8zN3o2MUxJV3RtbVQyRFB6MjlNZ3hwUkozdStxb2ViV3lECk40NEUzQ0ZYaUJsOUJpMjFXM3ZvY0NrN1FMbkM1ZFlhczlhVWpxdWNGaXhPTDBlMmR5WnBmMHl2RUJTMGtuWHYKcjFjdkxnUGpCcUU5OGlZY0dJanU4OWl4UXg1YjRlWFVPeHlhQjVCN0p2Mml3dmJGU0ZpR3VxdUtURXBHT0dLegoyOTArT3Fpd2ZZamd4TlVHZkhmR0Y5S1o4MlF1cXFib3dhVnZiNnA3Zy9lNlRZK3ZMcWc1cTFKQVhWRG50ZzBDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVMFZPUXYvSzduWGlHb3hRbApJTDE0NVFwSDRLa3dVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFuMi96Wlh5ZGgyRzBCbnRqWHFhTWtaV0hYV3p1UmFHRVZTbXB5NjVhcC94Wgpud1NTd3QxQVllZlFLY1dPZmpLNmova1ZuNkoyY1VHQkZJdm9ha0FHMGZEczVEcVUvbUk1VTl5dzBQVE83amxYCjU0cytFTWROVU43QTUvK1IyTDE2Qmp2U05FVTdHUXZMd29PYjlYaGs2bGZ5MS95ZjJSNUpILzZISXZlNXFJNnQKMW5EQnpkdENtcVRLSFhsajZKdkp0NDlMVVhlUDhsSGRlYkFuc00ydk4xU1hiV3NHVnZDSUtDbVdrWGZuNTJkdwpqbDZMS2FzQmFxSXR1bENydVl1b3JBT0xzMXNwWiswMVliKzFqV1NSMVFNSStBamJiaS9RSnlJMVZua2NnOGk0CmY0WElNNUl2V21hYXJsSUJMRTZHQWJITTJ2MlZsV2J0aFBZeW4yd3dnZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-httptrigger
  failurePolicy: Fail
  name: vhttptrigger.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - httptriggers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU8rdFRRMTJnWDM0MEpxb3ZIVkc3WG93RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXhORFV6TURKYUZ3MHpNVEExTURVeApORFV6TURKYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTU4zdkI4cXQ1b0xuT0tBQTdvc2xYTjUKREtmS3A5K1dCbkVPc0hYcGJVSXF0VncvSHdscWgrMkZnZmR2OGt2TDR3c3MweisyMjhmTHArblFRSnFzV3VGWgo5eGpFZ0d3bDBJWUNhVDdrc1RxY21jdU5DemxxZG8zN3o2MUxJV3RtbVQyRFB6MjlNZ3hwUkozdStxb2ViV3lECk40NEUzQ0ZYaUJsOUJpMjFXM3ZvY0NrN1FMbkM1ZFlhczlhVWpxdWNGaXhPTDBlMmR5WnBmMHl2RUJTMGtuWHYKcjFjdkxnUGpCcUU5OGlZY0dJanU4OWl4UXg1YjRlWFVPeHlhQjVCN0p2Mml3dmJGU0ZpR3VxdUtURXBHT0dLegoyOTArT3Fpd2ZZamd4TlVHZkhmR0Y5S1o4MlF1cXFib3dhVnZiNnA3Zy9lNlRZK3ZMcWc1cTFKQVhWRG50ZzBDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVMFZPUXYvSzduWGlHb3hRbApJTDE0NVFwSDRLa3dVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFuMi96Wlh5ZGgyRzBCbnRqWHFhTWtaV0hYV3p1UmFHRVZTbXB5NjVhcC94Wgpud1NTd3QxQVllZlFLY1dPZmpLNmova1ZuNkoyY1VHQkZJdm9ha0FHMGZEczVEcVUvbUk1VTl5dzBQVE83amxYCjU0cytFTWROVU43QTUvK1IyTDE2Qmp2U05FVTdHUXZMd29PYjlYaGs2bGZ5MS95ZjJSNUpILzZISXZlNXFJNnQKMW5EQnpkdENtcVRLSFhsajZKdkp0NDlMVVhlUDhsSGRlYkFuc00ydk4xU1hiV3NHVnZDSUtDbVdrWGZuNTJkdwpqbDZMS2FzQmFxSXR1bENydVl1b3JBT0xzMXNwWiswMVliKzFqV1NSMVFNSStBamJiaS9RSnlJMVZua2NnOGk0CmY0WElNNUl2V21hYXJsSUJMRTZHQWJITTJ2MlZsV2J0aFBZeW4yd3dnZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-kuberneteswatchtrigger
  failurePolicy: Fail
  name: vkuberneteswatchtrigger.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kuberneteswatchtriggers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU8rdFRRMTJnWDM0MEpxb3ZIVkc3WG93RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXhORFV6TURKYUZ3MHpNVEExTURVeApORFV6TURKYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTU4zdkI4cXQ1b0xuT0tBQTdvc2xYTjUKREtmS3A5K1dCbkVPc0hYcGJVSXF0VncvSHdscWgrMkZnZmR2OGt2TDR3c3MweisyMjhmTHArblFRSnFzV3VGWgo5eGpFZ0d3bDBJWUNhVDdrc1RxY21jdU5DemxxZG8zN3o2MUxJV3RtbVQyRFB6MjlNZ3hwUkozdStxb2ViV3lECk40NEUzQ0ZYaUJsOUJpMjFXM3ZvY0NrN1FMbkM1ZFlhczlhVWpxdWNGaXhPTDBlMmR5WnBmMHl2RUJTMGtuWHYKcjFjdkxnUGpCcUU5OGlZY0dJanU4OWl4UXg1YjRlWFVPeHlhQjVCN0p2Mml3dmJGU0ZpR3VxdUtURXBHT0dLegoyOTArT3Fpd2ZZamd4TlVHZkhmR0Y5S1o4MlF1cXFib3dhVnZiNnA3Zy9lNlRZK3ZMcWc1cTFKQVhWRG50ZzBDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVMFZPUXYvSzduWGlHb3hRbApJTDE0NVFwSDRLa3dVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFuMi96Wlh5ZGgyRzBCbnRqWHFhTWtaV0hYV3p1UmFHRVZTbXB5NjVhcC94Wgpud1NTd3QxQVllZlFLY1dPZmpLNmova1ZuNkoyY1VHQkZJdm9ha0FHMGZEczVEcVUvbUk1VTl5dzBQVE83amxYCjU0cytFTWROVU43QTUvK1IyTDE2Qmp2U05FVTdHUXZMd29PYjlYaGs2bGZ5MS95ZjJSNUpILzZISXZlNXFJNnQKMW5EQnpkdENtcVRLSFhsajZKdkp0NDlMVVhlUDhsSGRlYkFuc00ydk4xU1hiV3NHVnZDSUtDbVdrWGZuNTJkdwpqbDZMS2FzQmFxSXR1bENydVl1b3JBT0xzMXNwWiswMVliKzFqV1NSMVFNSStBamJiaS9RSnlJMVZua2NnOGk0CmY0WElNNUl2V21hYXJsSUJMRTZHQWJITTJ2MlZsV2J0aFBZeW4yd3dnZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-messagequeuetrigger
  failurePolicy: Fail
  name: vmessagequeuetrigger.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - messagequeuetriggers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU8rdFRRMTJnWDM0MEpxb3ZIVkc3WG93RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXhORFV6TURKYUZ3MHpNVEExTURVeApORFV6TURKYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTU4zdkI4cXQ1b0xuT0tBQTdvc2xYTjUKREtmS3A5K1dCbkVPc0hYcGJVSXF0VncvSHdscWgrMkZnZmR2OGt2TDR3c3MweisyMjhmTHArblFRSnFzV3VGWgo5eGpFZ0d3bDBJWUNhVDdrc1RxY21jdU5DemxxZG8zN3o2MUxJV3RtbVQyRFB6MjlNZ3hwUkozdStxb2ViV3lECk40NEUzQ0ZYaUJsOUJpMjFXM3ZvY0NrN1FMbkM1ZFlhczlhVWpxdWNGaXhPTDBlMmR5WnBmMHl2RUJTMGtuWHYKcjFjdkxnUGpCcUU5OGlZY0dJanU4OWl4UXg1YjRlWFVPeHlhQjVCN0p2Mml3dmJGU0ZpR3VxdUtURXBHT0dLegoyOTArT3Fpd2ZZamd4TlVHZkhmR0Y5S1o4MlF1cXFib3dhVnZiNnA3Zy9lNlRZK3ZMcWc1cTFKQVhWRG50ZzBDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVMFZPUXYvSzduWGlHb3hRbApJTDE0NVFwSDRLa3dVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFuMi96Wlh5ZGgyRzBCbnRqWHFhTWtaV0hYV3p1UmFHRVZTbXB5NjVhcC94Wgpud1NTd3QxQVllZlFLY1dPZmpLNmova1ZuNkoyY1VHQkZJdm9ha0FHMGZEczVEcVUvbUk1VTl5dzBQVE83amxYCjU0cytFTWROVU43QTUvK1IyTDE2Qmp2U05FVTdHUXZMd29PYjlYaGs2bGZ5MS95ZjJSNUpILzZISXZlNXFJNnQKMW5EQnpkdENtcVRLSFhsajZKdkp0NDlMVVhlUDhsSGRlYkFuc00ydk4xU1hiV3NHVnZDSUtDbVdrWGZuNTJkdwpqbDZMS2FzQmFxSXR1bENydVl1b3JBT0xzMXNwWiswMVliKzFqV1NSMVFNSStBamJiaS9RSnlJMVZua2NnOGk0CmY0WElNNUl2V21hYXJsSUJMRTZHQWJITTJ2MlZsV2J0aFBZeW4yd3dnZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-package
  failurePolicy: Fail
  name: vpackage.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - packages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lSQU8rdFRRMTJnWDM0MEpxb3ZIVkc3WG93RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS1ptbHpjMmx2YmkxallUQWVGdzB5TmpBMU1EWXhORFV6TURKYUZ3MHpNVEExTURVeApORFV6TURKYU1DWXhKREFpQmdOVkJBTVRHM2RsWW1odmIyc3RjMlZ5ZG1salpTNW1hWE56YVc5dUxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTU4zdkI4cXQ1b0xuT0tBQTdvc2xYTjUKREtmS3A5K1dCbkVPc0hYcGJVSXF0VncvSHdscWgrMkZnZmR2OGt2TDR3c3MweisyMjhmTHArblFRSnFzV3VGWgo5eGpFZ0d3bDBJWUNhVDdrc1RxY21jdU5DemxxZG8zN3o2MUxJV3RtbVQyRFB6MjlNZ3hwUkozdStxb2ViV3lECk40NEUzQ0ZYaUJsOUJpMjFXM3ZvY0NrN1FMbkM1ZFlhczlhVWpxdWNGaXhPTDBlMmR5WnBmMHl2RUJTMGtuWHYKcjFjdkxnUGpCcUU5OGlZY0dJanU4OWl4UXg1YjRlWFVPeHlhQjVCN0p2Mml3dmJGU0ZpR3VxdUtURXBHT0dLegoyOTArT3Fpd2ZZamd4TlVHZkhmR0Y5S1o4MlF1cXFib3dhVnZiNnA3Zy9lNlRZK3ZMcWc1cTFKQVhWRG50ZzBDCkF3RUFBYU9CdERDQnNUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVMFZPUXYvSzduWGlHb3hRbApJTDE0NVFwSDRLa3dVUVlEVlIwUkJFb3dTSUliZDJWaWFHOXZheTF6WlhKMmFXTmxMbVpwYzNOcGIyNHVjM1pqCmdpbDNaV0pvYjI5ckxYTmxjblpwWTJVdVptbHpjMmx2Ymk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFuMi96Wlh5ZGgyRzBCbnRqWHFhTWtaV0hYV3p1UmFHRVZTbXB5NjVhcC94Wgpud1NTd3QxQVllZlFLY1dPZmpLNmova1ZuNkoyY1VHQkZJdm9ha0FHMGZEczVEcVUvbUk1VTl5dzBQVE83amxYCjU0cytFTWROVU43QTUvK1IyTDE2Qmp2U05FVTdHUXZMd29PYjlYaGs2bGZ5MS95ZjJSNUpILzZISXZlNXFJNnQKMW5EQnpkdENtcVRLSFhsajZKdkp0NDlMVVhlUDhsSGRlYkFuc00ydk4xU1hiV3NHVnZDSUtDbVdrWGZuNTJkdwpqbDZMS2FzQmFxSXR1bENydVl1b3JBT0xzMXNwWiswMVliKzFqV1NSMVFNSStBamJiaS9RSnlJMVZua2NnOGk0CmY0WElNNUl2V21hYXJsSUJMRTZHQWJITTJ2MlZsV2J0aFBZeW4yd3dnZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    service:
      name: webhook-service
      namespace: fission
      path: /validate-fission-io-v1-timetrigger
  failurePolicy: Fail
  name: vtimetrigger.fission.io
  rules:
  - apiGroups:
    - fission.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - timetriggers
  sideEffects: None
