apiVersion: v1
data:
  global: "{\n  \"keepLatestMaintenanceJobs\": 3\n}\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-12.2.0
  name: velero-repo-maintenance
  namespace: velero
